### ISSUE TITLE
Add default exclusions for Maven and Gradle wrappers

### ISSUE THREAD

**Issue by hermitmaster** [ec4j/editorconfig-linters#8]
e.g.
```sh
.mvn/**/*
mvnw
mvnw.cmd
```
```sh
gradle/**/*
gradlew
gradlew.bat
```

**Comment by ppalaga** [comment]
@hermitmaster thanks for the suggestion. Could you please explain why we need this?

**Comment by hermitmaster** [comment]
There isn’t any rational argument for linting or formatting these things. They’re fundamentally equivalent to generated code.

**Comment by ppalaga** [comment]
> There isn’t any rational argument for linting or formatting these things. They’re fundamentally equivalent to generated code.

I agree that some of the mentioned files are typically generated, but not all. E.g. `.mvn/extensions.xml` is manually created much like `pom.xml`. 

Besides, I like having a rule for Windows batch files like

```
[*.{cmd,bat}]
end_of_line = crlf
```

so that misconfigured git does not break them by replacing EOLs for LF (some Windows git clients do this by default).

So -1 for me, sorry.
